### ISSUE TITLE
Allow creating human users. 

### ISSUE THREAD

**Issue by GuiBibeau** [GuiBibeau/sprout#10]
Currently, only assistants can be created and creating a human user is made from an helper script. Create an endpoint that allows registering users:

AC:

- create a POST endpoint at `/users`
- Restrict the endpoint to a bearer token. 
- restrict who can create a user, validate permissions 
- the endpoint should save that user in the database (neo4j)
- the endpoint attaches the right role and permissions to a user (redis)
- the endpoint returns an API key for that user

notes: have a look at existing endpoints and scripts as there are established patterns for this

**Comment by vimal20002** [comment]
Please assign this to me, I have dealt with these things a bunch of time.

**Comment by GuiBibeau** [comment]
@vimal20002 Feel free to submit a PR whenever you want! You can run the database locally with the docker compose files. We will have a contributor setup guiide coming in the next few days

**Comment by multipletwigs** [comment]
Hey @GuiBibeau I have a draft PR open up for this issue! It is here #24 though I do have some questions, that i'll ask soon!

**Comment by multipletwigs** [comment]
@GuiBibeau Do remember to close the issue, forgot to auto-close
