### ISSUE TITLE
Create a GPT-4 adapter

### ISSUE THREAD

**Issue by GuiBibeau** [GuiBibeau/sprout#11]
we need a way to send messages to GPT-4

AC:

- create an adapter under the adapter folders
- create the right configuration that reads an API key from env variables
- create a service that will send messages to GPT and accepts a response

**Comment by iampaandey** [comment]
Assign this issue to me,I have done the same in my projects.

**Comment by GuiBibeau** [comment]
@iampaandey sure have a go at it! Fork and open a PR once you are ready.

**Comment by GuiBibeau** [comment]
@iampaandey If you open a PR I will assign this to you. In the mean time I'll keep it unassigned in case anybody works on it
