### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by GuiBibeau** [GuiBibeau/sprout#15]
### Overview
We currently do not have a pull request template for our repository. Adding a template would help streamline the pull request process by ensuring key information is included.

Tasks
- [x] Create .github/PULL_REQUEST_TEMPLATE.md file
- [x] Add the following suggested sections:
    * Description of changes
    * Related issues
    * Testing done
    * Screenshots (if applicable)

**Comment by Jainil2004** [comment]
hi @GuiBibeau, I want to solve this issue and would love to contribute to this project. can you please assign me this issue?
thank you

**Comment by GuiBibeau** [comment]
@Jainil2004 feel free to open a PR and I will assign the issue

**Comment by Jainil2004** [comment]
thanks for the information. I will start working on the issue and will report back to you once I am done.

**Comment by Jainil2004** [comment]
hi @GuiBibeau I have opened a PR, please review it. Also do provide me with some feedback if there is something to be changed or improved. I'll be very happy to help and resolve any sort of problems. 
Thank you

**Comment by GuiBibeau** [comment]
@Jainil2004 thank you very much for taking this over! I left a few small comments but we are very close to a merge!
