### ISSUE TITLE
Transition to a monorepo

### ISSUE THREAD

**Issue by GuiBibeau** [GuiBibeau/sprout#26]
We will need soon to create dashboard UIs, a landing page etc. currently sprout is a backend only application. This issue is to move to a monorepo setup.

Acceptance Criteria:

- [ ] explore bun support for monorepos
- [ ] move the current code to a package under a mono repo
- [ ] update the readme properly
- [ ] create scripts at the top level to start the project quickly.

**Comment by tobySolutions** [comment]
This has been done @GuiBibeau!

**Comment by tobySolutions** [comment]
Fixed by #35
